
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoAnQLSV
{

using System;
    using System.Collections.Generic;
    
public partial class SinhVien
{

    public string maSinhVien { get; set; }

    public string hoDem { get; set; }

    public string ten { get; set; }

    public string lop { get; set; }

    public string gioiTinh { get; set; }

    public string email { get; set; }

    public string sdt { get; set; }

    public Nullable<int> phatBieu { get; set; }

    public Nullable<int> soBuoiVang { get; set; }

    public int soBuoiCoMat { get; set; }

    public int maLop { get; set; }



    public virtual Lop Lop { get; set; }

}

}
