
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DoAnQLSV
{

using System;
    using System.Collections.Generic;
    
public partial class TaiKhoan
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TaiKhoan()
    {

        this.Lops = new HashSet<Lop>();

    }


    public int maTaiKhoan { get; set; }

    public string taiKhoan1 { get; set; }

    public string matKhau { get; set; }

    public string ghiChu { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Lop> Lops { get; set; }

}

}
